### SIGNUP
POST http://localhost:3003/users/signup
Content-Type: application/json

{
    "name": "Pedro Sumaré",
    "email": "pedro.sumare@gmail.com",
    "password": "123456",
    "role": "NORMAL"
}


### LOGIN
POST http://localhost:3003/users/login
Content-Type: application/json

{
    "email": "grendene.lari@gmail.com",
    "password": "123456"
}
//yeu37ydlwq

### DELETE ACCOUNT
DELETE http://localhost:3003/users/63f532dd19defe5b5d95705a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjc4NGM1Y2E2MmUzYWFhYzg5OWIxZiIsInJvbGUiOiJBRE1JTiIsImlhdCI6MTY3NzE2NTg3NywiZXhwIjoxNjc3MTY5NDc3fQ.93rYiTIdhVE2Xkw-_h2zRc99GVDjAiGKLlynsrW1ZXc
Content-Type: application/json


### GET ACCOUNT INFORMATION
GET http://localhost:3003/users/account
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjc3MTdjMmQwZTFhZjBjOTI4NGU2ZiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzcyNzUxNTYsImV4cCI6MTY3NzI3ODc1Nn0.OIUFJdsPl3m5t8He21y_7imPy1c9rVr4HOaqXGLarZQ
Content-Type: application/json


### GET USER BY ID
GET http://localhost:3003/users/63f92ff13d0bc915472361d6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjc3MTdjMmQwZTFhZjBjOTI4NGU2ZiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzcyNzUxNTYsImV4cCI6MTY3NzI3ODc1Nn0.OIUFJdsPl3m5t8He21y_7imPy1c9rVr4HOaqXGLarZQ
Content-Type: application/json


### FOLLOW
PATCH http://localhost:3003/users/follow/63f7717c2d0e1af0c9284e6f
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjkyZmYxM2QwYmM5MTU0NzIzNjFkNiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzczNjU0NzksImV4cCI6MTY3NzM2OTA3OX0.uA13BEtaNdL8nA3CxYIFxnuEX6iI6cqs7JYXYg7L9wg
Content-Type: application/json


### UNFOLLOW
PATCH http://localhost:3003/users/unfollow/63f92ff13d0bc915472361d6
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjdiYmNiN2VlNTFhZmU2MjFkYWRlZCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzczNjM5NzYsImV4cCI6MTY3NzM2NzU3Nn0.ClWCBo-K1C-bPRlh-RWkbybXIiXZxn-ZfMRVpORLVgU
Content-Type: application/json


### CREATE RECIPE
POST http://localhost:3003/recipes/create
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjdiYmNiN2VlNTFhZmU2MjFkYWRlZCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzczNzE3NzAsImV4cCI6MTY3NzM3NTM3MH0._221PKcY2750FsHSHouC_QzZJaCU3eYMarC2WhxK8u8
Content-Type: application/json

{
    "title": "Pão de queijo",
    "description": "INGREDIENTES: 800 g de polvilho azedo, 1 xícara de água, 1 xícara de leite, 1/2 xícara de óleo, 2 ovos, 100 g de queijo parmesão ralado, sal a gosto. MODO DE PREPARO: Em uma panela, ferva a água e acrescente o leite, o óleo e o sal. Adicione o polvilho aos poucos até dar liga. Pode ser que você não precise usar os 800g, então coloque devagar e sove a massa até soltar da mão: esse é o ponto. Quando a massa estiver morna, acrescente o queijo parmesão, os ovos e misture bem. Unte as mãos e enrole bolinhas de 2 cm de diâmetro. Disponha as bolinhas em uma assadeira untada com óleo, deixando um espaço entre elas. Asse em forno médio (180º C), preaquecido, por cerca de 40 minutos."
}


### EDIT RECIPE
PUT http://localhost:3003/recipes/63fa86eec72419f269589e76
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjc3MTdjMmQwZTFhZjBjOTI4NGU2ZiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzczNjk4MTgsImV4cCI6MTY3NzM3MzQxOH0.o0aXeDU0Qy9EIDMT_ONHhgUj3mUxMw9VkthmdMlmvsE
Content-Type: application/json

{
    "title": "Empadão de frango 2"
}


### DELETE RECIPE
DELETE http://localhost:3003/recipes/63fa8845c72419f269589e7e
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjdiYmNiN2VlNTFhZmU2MjFkYWRlZCIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzczNzE3NzAsImV4cCI6MTY3NzM3NTM3MH0._221PKcY2750FsHSHouC_QzZJaCU3eYMarC2WhxK8u8
Content-Type: application/json


### GET RECIPES
GET http://localhost:3003/recipes
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjkyZmYxM2QwYmM5MTU0NzIzNjFkNiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzczNjU0NzksImV4cCI6MTY3NzM2OTA3OX0.uA13BEtaNdL8nA3CxYIFxnuEX6iI6cqs7JYXYg7L9wg
Content-Type: application/json


### GET RECIPE BY ID
GET http://localhost:3003/recipes/63fa87a2c72419f269589e7a
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYzZjkyZmYxM2QwYmM5MTU0NzIzNjFkNiIsInJvbGUiOiJOT1JNQUwiLCJpYXQiOjE2NzczNjYyMzcsImV4cCI6MTY3NzM2OTgzN30.fcaNXG8HbB5xamiLXdfppTDzvpwHLTeFcH8Pta_FKs4
Content-Type: application/json


### RECOVER PASSWORD
PATCH http://localhost:3003/users/recoverPassword
Content-Type: application/json

{
    "email": "contato@barkwhine.com.br"
}